/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

/**
 *
 * @author sala405
 */
public class Presentador extends javax.swing.JFrame {

    /**
     * Creates new form Presentador
     */
    public Presentador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1. Cual es el gentilicio de una persona nacida en Bélgica?", "Belgatorio", "Belganes", "Belganita", "BELGA"},
                {"2.Cual es el idioma oficial de Israel?", "Jpones", "Griego", "HEBREO", "Chino"},
                {"3.Así dice el trabalenguas: \"Un burro comía berros y el perro se los...\"", "Quito", "ROBO", "escondio", "Llevo"},
                {"4.Que parte del cuerpo se examina en una encefalografia?", "Ovarios", "CRANEO", "Pulmones", "Higado"},
                {"5.La coroides es una membrana que se encuentra en:", "EL OJO", "El corazon", "El pulmon", "El cerebro"},
                {"6.Cual es el dialecto originario del paraguay?", "GUARANI", "Español", "Queshua", "Chibcha"},
                {"7.Es el nombre de uno de los tres reyes magos", "Jugas", "MELCHOR", "Barrabas", "Jonas"},
                {"8.Segun la cancion de los hombres G, quien tiene un marcapasos", "MARTA", "Carla", "Laura", "Alba"},
                {"9.El albinismo se presenta por la carencia de:", "Vitamina A", "Calcio", "PIGMENTACION", "Oxigeno"},
                {"10.Donde se desarrollo la civilizacion etrusca", "Norte de africa", "PENINSULA ITALICA", "Caucaso", "Norte de oriente"},
                {"11.En la mitologia griega Eros es considerado el Dios de:", "AMOR", "Trabajo", "Odio", "Miedo"},
                {"12.La sede de los navegantes del magallanes queda en:", "Caracas", "VALENCIA", "Maracaibo", "Los teques"},
                {"13.Que pais de suramerica esta rodeado por el oceano atlantico y el oceano pacifico?", "COLOMBIA", "Brasil", "Argentina", "Uruguay"},
                {"14.Uno de ellos canta \"Vamos pa la conga...\"", "RICARDO MONTANER", "Guillermo davila", "Nino bravo", "Frank Quintero"},
                {"15.Cual de los siguientes documentos mide la densidad de los aceites", "Dinamometro", "Micrometro", "OLEOMETRO", "Holometro"}
            },
            new String [] {
                "Pregunta", "A", "B", "C", "D"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 11, 830, 275));

        jButton1.setText("Volver a intentar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Inicio b = new Inicio();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presentador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
